config/routes.rb
Budgie::Application.routes.draw do

  root 'sessions#new'
  resources :users
  resources :transactions
  match '/', to: 'sessions#create', via: 'post'
  match '/', to: 'sessions#destroy', via: 'delete'
  match '/about', to: 'static_pages#about', via: 'get' 
  match '/signup', to: 'users#new', via: 'get' 

  match '/myaccount', to: 'users#edit', via: 'get'
  match '/myaccount', to: 'users#update', via: 'post'

  match '/add_transaction', to: 'transactions#new', via: 'get'
  match '/edit_transaction', to: 'transactions#edit', via: 'get'
  match '/edit_transaction', to: 'transactions#destroy', via: 'delete'

  match '/signout', to: 'sessions#destroy', via: 'delete'
  match '/signout', to: 'sessions#destroy', via: 'get'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>

  <%= javascript_include_tag "//www.google.com/jsapi", "chartkick" %>
  <link href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap-glyphicons.css" rel="stylesheet">
  <title>Budgie</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>

    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <script src="http://code.highcharts.com/highcharts.js"></script>
  <%= csrf_meta_tags %>
</head>

<body>
	<% if signed_in? %>
 
  <div id="login_status">
    <%= render 'shared/login_message' %>
  </div>
  
<!--Header-->
<div id="header" class="navbar navbar-default">

    <!--Login Greeting-->
  <div class="container">
    <div class="float-left">
      <a href="/"><%= image_tag("logo_small.png", :alt => "budgie_logo") %></a>
    </div>
    <div class="float-right"><%= link_to raw('<button class="btn btn-primary btn-large" role="button">Sign Out</button>'), signout_path, method: "delete" %></div>

    </div>
  </div>

  <!-- Begin page content -->
  <div class="center-container">
    <div class="center-row">
      

        <!--LEFT SIDE-->

        <% @total = get_total %>

        <% if @total < 0 %>
          <div class="col-xs-6 left" style="background: url('<%= asset_path 'a.jpg' %>'); background-size: cover; background-position: center;">
        <% elsif @total >= 0 and @total < 500 %>
          <div class="col-xs-6 left" style="background: url('<%= asset_path 'b.jpeg' %>'); background-size: cover; background-position: center;">
        <% elsif @total >= 500  and @total < 1000 %>
          <div class="col-xs-6 left" style="background: url('<%= asset_path 'c.jpg' %>'); background-size: cover; background-position: center;">
        <% elsif @total >= 1000 %>
          <div class="col-xs-6 left" style="background: url('<%= asset_path 'd.jpg' %>'); background-size: cover; background-position: center;">
        <% else %>
          <div class="col-xs-6 left" style="background: url('<%= asset_path 'd.jpg' %>'); background-size: cover; background-position: center;">
        <% end %>

       <!--  <p>You have spent</p>
        <h1>59%</h1>
        <p>of your previous month's expenditure.</p> -->
        <p>You have saved</p>
        <h1>
        <% fake_total = @total %>
        <% if fake_total < 0 %>
          <% fake_total *= -1 %>-
        <% end %>
        <%= sprintf("$%.2f", fake_total) %></h1>
         <p>
          <% if current_user.date_type == "Day" %>
          <% if (current_user.date == Date.today) %>
          today
          <% else %>
          on <%= current_user.date %>
          <% end %>
          <% elsif current_user.date_type == "Week" %>

          <% if (Date.today <= current_user.date and current_user.date <= Date.today + 1.weeks) %>
            <p>this week</p>  
          <% else %>
            <p>on the week of <%= current_user.date.strftime("%A %B %e, %Y") %></p>
          <% end %>
          
          <% elsif current_user.date_type == "Month" %>
          <% if (current_user.date.month == Date.today.month and current_user.date.year == Date.today.year) %>
          this month
          <% else %>
          during <%= Date::MONTHNAMES[current_user.date.month] %> <%= current_user.date.year %>
          <% end %>
          <% elsif current_user.date_type == "Year" %>

          <% if (current_user.date.year == Date.today.year) %>
          this year
          <% else %>
          during <%= current_user.date.year %>
          <% end %>

          <% elsif current_user.date_type == "All" %>
          <p>overall</p>
          <% else %>
          <p>today</p>
          <% end %>
        </p>


<% if !@transactions.nil? and !@transactions.empty? %>
<div id="line-chart">
<script>
          Highcharts.setOptions({
            chart: {
              style: {
                fontFamily: '"Helvetica Neue", Helvetica, Arial, sans-serif'
              }
            }
          });
          $(function () {
            $('#line-chart').highcharts({
              chart: {
               backgroundColor: 'rgba(255, 255, 255, 0.7)'
              },
              title: {
                <% if (current_user.date_type == "Day") %>
                text: 'Daily Spending'
                <% elsif (current_user.date_type == "Week") %>
                text: 'Weekly Spending'
                <% elsif (current_user.date_type == "Month") %>
                text: 'Monthly Spending'
                <% elsif (current_user.date_type == "Year") %>
                text: 'Yearly Spending'
                <% elsif (current_user.date_type == "All") %>
                text: 'Overall Spending'
                <% end %>
                ,
           //center
          },
          subtitle: {

            x: -20
          },
          xAxis: {
            categories: <%= raw @date_list %>
          },
          yAxis: {
            title: {
              text: 'Money'
            },
            plotLines: [{
              value: 0,
              width: 1,
              color: '#808080'
            }]
          },
          tooltip: {
            // valuePrefix: '$'
          },
          legend: {
            layout: 'vertical',
            align: 'right',
            verticalAlign: 'middle',
            borderWidth: 0
          },
          series: [{
            name: 'Savings',
            data: <%= raw @date_transaction_list %>
          }]
        });

}
);
</script>
</div>

<div id="pie-chart">
<script>

$(function () {
    $('#pie-chart').highcharts({
        chart: {
            backgroundColor: 'rgba(255, 255, 255, 0.7)',
            plotBackgroundColor: null,
            plotBorderWidth: 1,//null,
            plotShadow: false

        },
        title: {
            text: 'Transactions by Category'
        },
        tooltip: {
            pointFormat: '{series.name}: <b>{point.percentage:.1f}%</b>'
        },
        plotOptions: {
            pie: {
                allowPointSelect: true,
                cursor: 'pointer',
                dataLabels: {
                    enabled: true,
                    format: '<b>{point.name}</b>: {point.percentage:.1f}%',
                    style: {
                        color: (Highcharts.theme && Highcharts.theme.contrastTextColor) || 'black'
                    }
                }
            }
        },
        series: [{
            type: 'pie',
            name: 'Transaction',
            data: [
                <% @category_hash.keys.each do |c| %>
                  ["<%= raw c %>", <%= @category_hash[c] %>]
                  <% if c != @category_hash.keys.last %>
                  ,
                  <% end %>
               

                <% end %>
      
            ]
        }]
    });
});

</script>

</div>

<% end %>


      </div>

      <!--RIGHT SIDE-->
      <div class="col-xs-6 right">

        <div class="btn-group-vertical float-left" id="icons">

            <%= link_to raw('<span class="glyphicon glyphicon-plus"></span>'), new_transaction_path, method: "get", class: 'btn btn-large btn-lg"' %>
          
            <%= link_to raw('<span class="glyphicon glyphicon-cog"></span>'), myaccount_path, method: "get", class: 'btn btn-large btn-lg' %>

        </div>

        <%= yield %>

      </div>
    </div>
  </div>
  <% else %>

  <%= yield %>

  <% end %>
  
</body>
</html>